name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - alpha
      - beta
      - main
      - master
      - renovate/**
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-RC[0-9]+'

jobs:
  ci-optimization:
    name: CI optimization
    uses: dargmuesli/github-actions/.github/workflows/ci-optimization.yml@b24aec150dd9a8562cd773dbd85487e56e46fdc6 # 5.7.0
    permissions:
      pull-requests: read
  build:
    needs: ci-optimization
    if: needs.ci-optimization.outputs.continue == 'true'
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        java: ["17", "25"]
    steps:
      - name: Checkout git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # fetch complete history to find the last git tag
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          cache: maven
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/') && matrix.java == 17
        env:
          GPG_KEY_NAME: B70E1EAC
          GPG_PASSPHRASE_FILE: ${{ secrets.GPG_PASSPHRASE_FILE }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: |
          ./ci/before-deploy.sh
          cp ./ci/.m2.settings.xml $HOME/.m2/settings.xml
          mvn deploy -P release -DskipTests=true
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && matrix.java == 17
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
